/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.appsms;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author khalila
 */
public final class Laporanpaket extends javax.swing.JFrame {
    
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form Laporanpaket
     */
    public Laporanpaket() {
        initComponents();
        tbltpaket.setModel(model);
        model.addColumn("NO");
        model.addColumn("Pembelian");
        model.addColumn("Nomor");
        model.addColumn("Waktu");
        model.addColumn("Status");
        model.addColumn("Keterangan");
        ambillaporan();
        
        lebarKolom();
    }
    
     public void ambillaporan(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        try{
//            java.sql.Connection c = KoneksiDatabase.koneksiDB();
//            java.sql.Statement s = c.createStatement();
//            int no=1;
//            String sql = "SELECT * FROM trans_pulsa";
//            java.sql.ResultSet hasil = s.executeQuery(sql);
            int no =1;
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pulsa","root","");
            try (java.sql.Statement s = con.createStatement()) {
                String sql = "SELECT * FROM trans_pulsa WHERE jenis='Paket Data'";
                try (java.sql.ResultSet hasil = s.executeQuery(sql)) {
                    while(hasil.next()){
                        Object[] o = new Object[6];
                        o[0] = no++;
                        o[1] = hasil.getString(2);
                        o[2] = hasil.getString(3);
                        o[3] = hasil.getString(4);
                        o[4] = hasil.getString(5);
                        o[5] = hasil.getString(6);
                        model.addRow(o);
                    }
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void lebarKolom(){
        TableColumn kolom;
        tbltpaket.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kolom = tbltpaket.getColumnModel().getColumn(0);
        kolom.setPreferredWidth(30);
        kolom.setMaxWidth(30);
        kolom = tbltpaket.getColumnModel().getColumn(1);
        kolom.setPreferredWidth(190);
        kolom.setMaxWidth(190);
        kolom = tbltpaket.getColumnModel().getColumn(2);
        kolom.setPreferredWidth(150);
        kolom.setMaxWidth(150);
        kolom = tbltpaket.getColumnModel().getColumn(3);
        kolom.setPreferredWidth(170);
        kolom.setMaxWidth(170);
        kolom = tbltpaket.getColumnModel().getColumn(5);
        kolom.setPreferredWidth(200);
        kolom.setMaxWidth(200);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        judul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltpaket = new javax.swing.JTable();
        tombolHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Pulsa = new javax.swing.JMenu();
        Paket = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        Lpulsa = new javax.swing.JMenuItem();
        Lpaket = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        judul.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        judul.setText("Laporan Penjualan Paket Data");

        tbltpaket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltpaket);

        tombolHome.setText("Home");
        tombolHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHomeActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Pulsa.setText("Pulsa");
        Pulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulsaActionPerformed(evt);
            }
        });
        jMenuBar1.add(Pulsa);

        Paket.setText("Paket Data");
        Paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaketActionPerformed(evt);
            }
        });
        jMenuBar1.add(Paket);

        Laporan.setText("Laporan Penjualan");

        Lpulsa.setText("Laporan Pulsa");
        Lpulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpulsaActionPerformed(evt);
            }
        });
        Laporan.add(Lpulsa);

        Lpaket.setText("Laporan Paket Data");
        Lpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpaketActionPerformed(evt);
            }
        });
        Laporan.add(Lpaket);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolHome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(tombolHome)
                        .addGap(43, 43, 43))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        this.hide();
    }//GEN-LAST:event_HomeActionPerformed

    private void PulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulsaActionPerformed
        // TODO add your handling code here:
        Appform pulsa = new Appform();
        pulsa.show();
        this.hide();
    }//GEN-LAST:event_PulsaActionPerformed

    private void PaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaketActionPerformed
        // TODO add your handling code here:
        Paket paket = new Paket();
        paket.show();
        this.hide();
    }//GEN-LAST:event_PaketActionPerformed

    private void LpulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpulsaActionPerformed
        // TODO add your handling code here:
        Laporanpulsa lp = new Laporanpulsa();
        lp.show();
        this.hide();
    }//GEN-LAST:event_LpulsaActionPerformed

    private void LpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpaketActionPerformed
        // TODO add your handling code here:
        Laporanpaket lpa = new Laporanpaket();
        lpa.show();
        this.hide();
    }//GEN-LAST:event_LpaketActionPerformed

    private void tombolHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHomeActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        this.hide();
        hm.show();
    }//GEN-LAST:event_tombolHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporanpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporanpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporanpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporanpaket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporanpaket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Home;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem Lpaket;
    private javax.swing.JMenuItem Lpulsa;
    private javax.swing.JMenu Paket;
    private javax.swing.JMenu Pulsa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel judul;
    private javax.swing.JTable tbltpaket;
    private javax.swing.JButton tombolHome;
    // End of variables declaration//GEN-END:variables
}
