/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.appsms;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author khalila
 */
public final class Laporanpulsa extends javax.swing.JFrame {

  DefaultTableModel model = new DefaultTableModel();
    
    /**
     * Creates new form Laporanpulsa
     */
    public Laporanpulsa() {
        initComponents();
        
        tbltpulsa.setModel(model);
        model.addColumn("NO");
        model.addColumn("Pembelian");
        model.addColumn("Nomor");
        model.addColumn("Waktu");
        model.addColumn("Status");
        model.addColumn("Keterangan");
        ambillaporan();
        
        lebarKolom();
    }
    public void ambillaporan(){
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        int no = 1;
        try{
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/pulsa","root","");
            try (java.sql.Statement s = con.createStatement()) {
                String sql = "SELECT * FROM trans_pulsa WHERE jenis='pulsa'";
                try (java.sql.ResultSet hasil = s.executeQuery(sql)) {
                    while(hasil.next()){
                        Object[] o = new Object[6];
                        o[0] = no++;
                        o[1] = hasil.getString(2);
                        o[2] = hasil.getString(3);
                        o[3] = hasil.getString(4);
                        o[4] = hasil.getString(5);
                        o[5] = hasil.getString(6);
                        model.addRow(o);
                    }
                }
            }
        }catch(Exception e){
            System.out.println(e.getMessage());
        }
    }
    
    public void lebarKolom(){
        TableColumn kolom;
        tbltpulsa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kolom = tbltpulsa.getColumnModel().getColumn(0);
        kolom.setPreferredWidth(30);
        kolom.setMaxWidth(30);
        kolom = tbltpulsa.getColumnModel().getColumn(1);
        kolom.setPreferredWidth(170);
        kolom.setMaxWidth(170);
        kolom = tbltpulsa.getColumnModel().getColumn(2);
        kolom.setPreferredWidth(150);
        kolom.setMaxWidth(150);
        kolom = tbltpulsa.getColumnModel().getColumn(3);
        kolom.setPreferredWidth(170);
        kolom.setMaxWidth(170);
        kolom = tbltpulsa.getColumnModel().getColumn(5);
        kolom.setPreferredWidth(200);
        kolom.setMaxWidth(200);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("pulsa?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        tblTransaksiQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT t FROM TblTransaksi t");
        tblTransaksiList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : tblTransaksiQuery.getResultList();
        Judul = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbltpulsa = new javax.swing.JTable();
        tombolHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Pulsa = new javax.swing.JMenu();
        Paket = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        Lpulsa = new javax.swing.JMenuItem();
        Lpaket = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Judul.setFont(new java.awt.Font("Lohit Devanagari", 1, 18)); // NOI18N
        Judul.setText("Laporan Penjualan Pulsa");

        tbltpulsa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbltpulsa);

        tombolHome.setText("Home");
        tombolHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHomeActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Pulsa.setText("Pulsa");
        Pulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulsaActionPerformed(evt);
            }
        });
        jMenuBar1.add(Pulsa);

        Paket.setText("Paket Data");
        Paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaketActionPerformed(evt);
            }
        });
        jMenuBar1.add(Paket);

        Laporan.setText("Laporan Penjualan");

        Lpulsa.setText("Laporan Pulsa");
        Lpulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpulsaActionPerformed(evt);
            }
        });
        Laporan.add(Lpulsa);

        Lpaket.setText("Laporan Paket Data");
        Lpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpaketActionPerformed(evt);
            }
        });
        Laporan.add(Lpaket);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolHome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolHome)
                    .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        this.hide();
    }//GEN-LAST:event_HomeActionPerformed

    private void PulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulsaActionPerformed
        // TODO add your handling code here:
        Appform pulsa = new Appform();
        pulsa.show();
        this.hide();
    }//GEN-LAST:event_PulsaActionPerformed

    private void PaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaketActionPerformed
        // TODO add your handling code here:
        Paket paket = new Paket();
        paket.show();
        this.hide();
    }//GEN-LAST:event_PaketActionPerformed

    private void LpulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpulsaActionPerformed
        // TODO add your handling code here:
        Laporanpulsa lp = new Laporanpulsa();
        lp.show();
        this.hide();
    }//GEN-LAST:event_LpulsaActionPerformed

    private void LpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpaketActionPerformed
        // TODO add your handling code here:
        Laporanpaket lpa = new Laporanpaket();
        lpa.show();
        this.hide();
    }//GEN-LAST:event_LpaketActionPerformed

    private void tombolHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHomeActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        this.hide();
        hm.show();
    }//GEN-LAST:event_tombolHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Laporanpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Laporanpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Laporanpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Laporanpulsa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Laporanpulsa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Home;
    private javax.swing.JLabel Judul;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem Lpaket;
    private javax.swing.JMenuItem Lpulsa;
    private javax.swing.JMenu Paket;
    private javax.swing.JMenu Pulsa;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.util.List<com.mycompany.appsms.TblTransaksi> tblTransaksiList;
    private javax.persistence.Query tblTransaksiQuery;
    private javax.swing.JTable tbltpulsa;
    private javax.swing.JButton tombolHome;
    // End of variables declaration//GEN-END:variables
}
