/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.appsms;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author khalila
 */
public class Paket extends javax.swing.JFrame implements WebSocketListener {
    private SmsGatewayClient client;
    /**
     * Creates new form Paket
     */
    public Paket() {
        initComponents();
          try{
            client = new SmsGatewayClient(new URI("ws://192.168.43.1:6868"), this);
            client.connectBlocking();
        }catch(URISyntaxException | InterruptedException e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Operator = new javax.swing.JComboBox();
        Nominal = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLog = new javax.swing.JTextArea();
        jButtonSend = new javax.swing.JButton();
        tombolHome = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        Pulsa = new javax.swing.JMenu();
        Paket = new javax.swing.JMenu();
        Laporan = new javax.swing.JMenu();
        Lpulsa = new javax.swing.JMenuItem();
        Lpaket = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("FORM PEMBELIAN PULSA SIPULsa");

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/khalila/Downloads/Sipulsa.png")); // NOI18N

        jLabel1.setText("Pilih Operator Paket Data");

        jLabel2.setText("Nominal Pulsa");

        jTextFieldTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToActionPerformed(evt);
            }
        });

        jLabel3.setText("Nomor yang akan di Isi");

        Operator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Axis", "Tri", "Indosat", "Telkomsel", "Xl" }));
        Operator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperatorActionPerformed(evt);
            }
        });

        Nominal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 GB", "2 GB", "5 GB", "10 GB", "15 GB", "17 GB", "20 GB", "50 GB", "75 GB", "100 GB", " ", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Operator, javax.swing.GroupLayout.Alignment.LEADING, 0, 365, Short.MAX_VALUE)
                    .addComponent(Nominal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Operator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Nominal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextAreaLog.setColumns(20);
        jTextAreaLog.setRows(5);
        jScrollPane2.setViewportView(jTextAreaLog);

        jButtonSend.setText("KIRIM");
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSend)
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 889, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButtonSend)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tombolHome.setText("Home");
        tombolHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHomeActionPerformed(evt);
            }
        });

        Home.setText("Home");
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        Pulsa.setText("Pulsa");
        Pulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PulsaActionPerformed(evt);
            }
        });
        jMenuBar1.add(Pulsa);

        Paket.setText("Paket Data");
        Paket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaketActionPerformed(evt);
            }
        });
        jMenuBar1.add(Paket);

        Laporan.setText("Laporan Penjualan");

        Lpulsa.setText("Laporan Pulsa");
        Lpulsa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpulsaActionPerformed(evt);
            }
        });
        Laporan.add(Lpulsa);

        Lpaket.setText("Laporan Paket Data");
        Lpaket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LpaketActionPerformed(evt);
            }
        });
        Laporan.add(Lpaket);

        jMenuBar1.add(Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolHome, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolHome)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldToActionPerformed

    private void OperatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperatorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OperatorActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        // TODO add your handling code here:
        String operator, nominal, message;
        operator = (String) Operator.getSelectedItem();
        nominal = (String) Nominal.getSelectedItem();

        message =  "Selamat Pengisian Pulsa "+operator+" Senilai "+nominal+" Berhasil.Jangan Bosan Beli di SIPULsa ya <3";
        //        //buatjson
        JsonObject object = new JsonObject();
        object.add("message", new JsonPrimitive(message));

        //cek apakah broadcast
        if(jTextFieldTo.getText().contains(",")){
            String[] tos = jTextFieldTo.getText().split(",");
            JsonArray array = new JsonArray();
            for(String to : tos){
                array.add(new JsonPrimitive(to));
            }
            object.add("to", array);
        }else {
            //bukan bc

            object.add("to", new JsonPrimitive(jTextFieldTo.getText()));
        }

        //konversi jadi  json
        String json = gson.toJson(object);

        //kirim ke server
        client.send(json);
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
        // TODO add your handling code here:
        Home home = new Home();
        home.show();
        this.hide();
    }//GEN-LAST:event_HomeActionPerformed

    private void PulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PulsaActionPerformed
        // TODO add your handling code here:
        Appform pulsa = new Appform();
        pulsa.show();
        this.hide();
    }//GEN-LAST:event_PulsaActionPerformed

    private void PaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaketActionPerformed
        // TODO add your handling code here:
        Paket paket = new Paket();
        paket.show();
        this.hide();
    }//GEN-LAST:event_PaketActionPerformed

    private void LpulsaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpulsaActionPerformed
        // TODO add your handling code here:
        Laporanpulsa lp = new Laporanpulsa();
        lp.show();
        this.hide();
    }//GEN-LAST:event_LpulsaActionPerformed

    private void LpaketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LpaketActionPerformed
        // TODO add your handling code here:
        Laporanpaket lpa = new Laporanpaket();
        lpa.show();
        this.hide();
    }//GEN-LAST:event_LpaketActionPerformed

    private void tombolHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHomeActionPerformed
        // TODO add your handling code here:
        Home hm = new Home();
        this.hide();
        hm.show();
    }//GEN-LAST:event_tombolHomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Home;
    private javax.swing.JMenu Laporan;
    private javax.swing.JMenuItem Lpaket;
    private javax.swing.JMenuItem Lpulsa;
    private javax.swing.JComboBox Nominal;
    private javax.swing.JComboBox Operator;
    private javax.swing.JMenu Paket;
    private javax.swing.JMenu Pulsa;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLog;
    private javax.swing.JTextField jTextFieldTo;
    private javax.swing.JButton tombolHome;
    // End of variables declaration//GEN-END:variables

    @Override
    public void onOpen() {
         jTextAreaLog.setAutoscrolls(true);
        jTextAreaLog.append("Koneksi ke server berhasil");
        jTextAreaLog.append("\n");
    }

    @Override
    public void onClose() {
         jTextAreaLog.setAutoscrolls(true);
        jTextAreaLog.append("Koneksi ke server terputus");
        jTextAreaLog.append("\n");
    }

    @Override
    public void onError() {
          jTextAreaLog.setAutoscrolls(true);
        jTextAreaLog.append("Ups, terjasi error di Koneksi");
        jTextAreaLog.append("\n");
    }
    
    private Gson gson = new Gson();

    @Override
    public void onMessage(String message) {
        JsonObject json = gson.fromJson(message, JsonObject.class);
        if(json.get("type").getAsString().equals("success")){
            String msg = json.get("message").getAsString();
            JOptionPane.showMessageDialog(this, msg);
        }else if(json.get("type").getAsString().equals("error")){
            String msg = json.get("message").getAsString();
            JOptionPane.showMessageDialog(this, msg);
        }else if(json.get("type").getAsString().equals("notification")) {
            String msg = json.get("message").getAsString();
            jTextAreaLog.setAutoscrolls(true);
            if(json.get("success").getAsBoolean()){
                String operator, nominal, nomor;
                operator = (String) Operator.getSelectedItem();
                nominal = (String) Nominal.getSelectedItem();
                nomor = (String) jTextFieldTo.getText();
                
                jTextAreaLog.append("Laporan pengiriman sukses : " + msg);
            try{java.sql.Statement statement = Koneksi.getConnection().createStatement();
                statement.executeUpdate("INSERT INTO tbl_transaksi(nama_produk, jenis_produk, Nominal, nomor, status) "
                        + "VALUES('"+operator+"','Paket Data', '"+nominal+"', '"+nomor+"', 'Sukses')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Transaksi Berhasil");
            }catch(Exception e){
            }
            }else{
                String operator, nominal, nomor;
                operator = (String) Operator.getSelectedItem();
                nominal = (String) Nominal.getSelectedItem();
                nomor = (String) jTextFieldTo.getText();
                jTextAreaLog.append("Laporan pengiriman gagal : " + msg);
                try{java.sql.Statement statement = Koneksi.getConnection().createStatement();
                statement.executeUpdate("INSERT INTO tbl_transaksi(nama_produk, jenis_produk, Nominal, nomor, status, keterangan) "
                        + "VALUES('"+operator+"','Paket Data', '"+nominal+"', '"+nomor+"', 'Gagal', '"+msg+"')");
                statement.close();
                JOptionPane.showMessageDialog(null, "Upps Sepertinya ada masalah,");
            }catch(Exception e){
            }
            }
            jTextAreaLog.append("\n");
        }else if(json.get("type").getAsString().equals("received")){
            String msg = json.get("message").getAsString();
            String from = json.get("from").getAsString();
            
            int result = JOptionPane.showConfirmDialog(this, new String[]{
                "SMS dari " + from + " dengan pesan : ",
                msg,
                "Apakah ingin dibalas?"
            });
            
            if(result == JOptionPane.OK_OPTION){
                jTextFieldTo.setText(from);
//                jTextAreaMessage.setText("");
            }
        }
    }
}
